# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MSBDD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MSBDD

  target 'MSBDDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MSBDDUITests' do
	pod 'Cucumberish'
    # Pods for testing
  end

end
