# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for practice
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
  pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'

  pod 'FirebaseFirestoreSwift', '> 7.0-beta'

  target 'practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'practiceUITests' do
    # Pods for testing
  end

end
